title = "Marcela Viola"
languagecode = "en_US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

baseurl = "http://natos.github.io/marcelaviola.com.ar"

relativeurls = false
canonifyurls = true
watch = true

[author]
  name = "Natan Santolo"

[params]
  description = "Aerialist, silks, lyra, and straps."

[taxonomies]
  category = "categories"
  tag = "tags"


SectionPagesMenu = "main"

[[menu.main]]
  name = "Shows"
  identifier = "shows"
  url = "/shows"
  weight = 1
[[menu.main]]
  name = "Classes"
  identifier = "classes"
  url = "/classes"
  weight = 2
[[menu.main]]
  name = "Workshops"
  identifier = "workshops"
  url = "/workshops"
  weight = 3
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "https://medium.com/@marcelaviola"
  weight = 4
[[menu.main]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"
  weight = 10