title = "Esi Bildosola"
baseurl = "http://www.esibildosola.com"
[params]
  description = "Esi Personal Trainer. One body. One Trainer."
  keywords = "Esi, Sports, Crossfit, JustFit, JustFit.vienna, yoga, modeling"

languagecode = "en_US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
relativeurls = false
canonifyurls = true
watch = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[author]
  name = "Natan Santolo"
