title = "Marcela Viola"
languagecode = "en_US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

baseurl = "http://natos.github.io/marcelaviola.com.ar"

relativeurls = false
canonifyurls = true
watch = true

[author]
  name = "Natan Santolo"

[params]
  description = "Aerialist, silks, lyra, and straps."

[taxonomies]
  category = "categories"
  tag = "tags"


SectionPagesMenu = "main"

[[menu.main]]
  weight = 0
  name = "About"
  url = "/"
[[menu.main]]
  weight = 1
  name = "Shows"
  url = "/shows/"
[[menu.main]]
  weight = 2
  name = "Classes"
  url = "/classes/"
[[menu.main]]
  weight = 3
  name = "Workshops"
  url = "/workshops/"
[[menu.main]]
  pre = "<i class=\"fa fa-envelope-o\"></i>"
  weight = 10
  name = "Contact"
  url = "/contact/"
